import { beforeAll,describe,expect,it,vi } from "vitest";
import { DOMParser } from "linkedom";
import { ADMIN_CONCURRENCY,ADMIN_PATHS,adminUrl,scanAdminSurfaces } from "./admin-surface";
import { parseTarget } from "../../core/target";
const target=parseTarget("https://fixture.test/base");
beforeAll(()=>vi.stubGlobal("DOMParser",DOMParser));
const response=(url:string,status:number,body:string,headers={"content-type":"text/html"})=>{const value=new Response(body,{status,headers});Object.defineProperty(value,"url",{value:url});return value};
describe("admin surface scanner",()=>{
  it("keeps a small unique registry and same-origin URLs",()=>{expect(ADMIN_PATHS.length).toBeGreaterThanOrEqual(20);expect(ADMIN_PATHS.length).toBeLessThanOrEqual(35);expect(new Set(ADMIN_PATHS).size).toBe(ADMIN_PATHS.length);expect(adminUrl(target,"/admin")).toBe("https://fixture.test/admin")});
  it("classifies likely, protected, redirect, not found and soft-404",async()=>{const fetcher=async(input:RequestInfo|URL)=>{const url=String(input),path=new URL(url).pathname;if(path.startsWith("/.kagetarget"))return response(url,200,"<title>SPA</title><main>same</main>");if(path==="/admin/")return response(url,200,'<title>Administration</title><form><input type="password"></form>');if(path==="/administrator/")return response(url,403,"");if(path==="/login")return response("https://fixture.test/auth/signin",200,"<title>Sign in</title>");if(path==="/random")return response(url,404,"");return response(url,200,"<title>SPA</title><main>same</main>")};const result=await scanAdminSurfaces(target,{signal:new AbortController().signal,fetcher:fetcher as typeof fetch,paths:["/admin/","/administrator/","/login","/random","/spa/admin"],probe:"/.kagetarget-probe-test"});expect(result.map(x=>x.classification)).toEqual(["LIKELY","PROTECTED","REDIRECT","NOT_FOUND","UNLIKELY"])});
  it("bounds concurrency, omits credentials, uses safe methods and aborts",async()=>{let active=0,max=0;const methods:string[]=[],credentials:(RequestCredentials|undefined)[]=[];const fetcher=async(input:RequestInfo|URL,init?:RequestInit)=>{active++;max=Math.max(max,active);methods.push(String(init?.method));credentials.push(init?.credentials);await new Promise(r=>setTimeout(r,2));active--;return response(String(input),404,"",{"content-type":"text/plain"})};await scanAdminSurfaces(target,{signal:new AbortController().signal,fetcher:fetcher as typeof fetch,paths:["/a","/b","/c","/d"],probe:"/.kagetarget-probe-test"});expect(max).toBeLessThanOrEqual(ADMIN_CONCURRENCY);expect(methods.every(x=>x==="HEAD"||x==="GET")).toBe(true);expect(credentials.every(x=>x==="omit")).toBe(true)});
});
