import type { TargetContext } from "../../types";

export type WaybackScope="host"|"root";
export type WaybackType="HTML"|"JS"|"JSON"|"CSS"|"API"|"DOCS"|"IMAGES"|"ARCHIVE"|"OTHER";
export type WaybackStatus="all"|"2xx"|"3xx"|"4xx"|"5xx"|"unknown";
export type WaybackSort="path"|"newest"|"oldest"|"status"|"type";
export interface WaybackRecord {timestamp:string;original:string;status:number|null;mimetype:string;digest:string;path:string;date:string;type:WaybackType;extension:string;hasParams:boolean;isApiLike:boolean;isInteresting:boolean;searchText:string}
export interface WaybackFilters {search:string;status:WaybackStatus;type:"ALL"|WaybackType;interesting:boolean;params:boolean;sort:WaybackSort}
export interface WaybackPage {records:WaybackRecord[];hasMore:boolean;page:number;rawCount:number}

const API_RULES=[/\/api(?:\/|$)/i,/\/graphql(?:\/|$)/i,/\/rest(?:api)?(?:\/|$)/i,/\/ajax(?:\/|$)/i,/\/wp-json(?:\/|$)/i];
const INTERESTING_RULES=[/\/(?:admin|login|auth|upload|download|export|import|backup|config|debug)(?:\/|$)/i,...API_RULES];
const INTERESTING_EXTENSIONS=new Set(["bak","old","backup","zip","tar","gz","sql","log","env"]);

export function rootDomain(hostname:string){const parts=hostname.toLowerCase().split(".").filter(Boolean);const commonSecondLevel=new Set(["co.uk","com.tr","com.au","co.jp","com.br"]);const lastTwo=parts.slice(-2).join(".");return commonSecondLevel.has(lastTwo)&&parts.length>2?parts.slice(-3).join("."):lastTwo||hostname}
export function waybackScope(target:TargetContext,scope:WaybackScope){return `${scope==="root"?rootDomain(target.hostname):target.hostname}/*`}
export function buildCdxUrl(target:TargetContext,scope:WaybackScope,page=0,limit=500){const url=new URL("https://web.archive.org/cdx/search/cdx");const params=url.searchParams;params.set("url",waybackScope(target,scope));params.set("output","json");params.set("fl","timestamp,original,statuscode,mimetype,digest");params.set("filter","statuscode:.*");params.set("collapse","urlkey");params.set("page",String(page));params.set("limit",String(limit));return url}
export function archiveUrl(record:Pick<WaybackRecord,"timestamp"|"original">){return `https://web.archive.org/web/${record.timestamp}id_/${record.original}`}

export function classifyArchivedUrl(original:string,mimetype=""){let parsed:URL;try{parsed=new URL(original)}catch{parsed=new URL("https://invalid.local/")};const path=parsed.pathname,extension=(path.match(/\.([a-z0-9]+)$/i)?.[1]??"").toLowerCase();const isApiLike=API_RULES.some(rule=>rule.test(path));let type:WaybackType="OTHER";if(isApiLike)type="API";else if(["js","mjs"].includes(extension))type="JS";else if(["json","xml"].includes(extension)||/json|xml/i.test(mimetype))type="JSON";else if(extension==="css")type="CSS";else if(["pdf","doc","docx","xls","xlsx","csv","txt"].includes(extension))type="DOCS";else if(["png","jpg","jpeg","gif","svg","webp","ico"].includes(extension)||/image/i.test(mimetype))type="IMAGES";else if(["zip","tar","gz"].includes(extension))type="ARCHIVE";else if(!extension||["html","htm","php","asp","aspx","jsp"].includes(extension)||/html/i.test(mimetype))type="HTML";return{type,hasParams:Boolean(parsed.search),isApiLike,isInteresting:INTERESTING_RULES.some(rule=>rule.test(path))||INTERESTING_EXTENSIONS.has(extension),extension,path:`${parsed.pathname}${parsed.search}`}}
export function parseCdxJson(value:unknown,page=0,limit=500):WaybackPage{if(!Array.isArray(value))throw new Error("INVALID_RESPONSE");const rows=value[0]?.[0]==="timestamp"?value.slice(1):value;const records:WaybackRecord[]=[];const seen=new Set<string>();for(const row of rows){if(!Array.isArray(row)||row.length<5)continue;const [timestamp,original,statuscode,mimetype,digest]=row.map(String);if(!/^\d{14}$/.test(timestamp)||!/^https?:\/\//i.test(original)||seen.has(original))continue;seen.add(original);const classified=classifyArchivedUrl(original,mimetype);records.push({timestamp,original,status:/^\d{3}$/.test(statuscode)?Number(statuscode):null,mimetype,digest,...classified,date:`${timestamp.slice(0,4)}-${timestamp.slice(4,6)}-${timestamp.slice(6,8)}`,searchText:original.toLowerCase()})}return{records,hasMore:rows.length>=limit,page,rawCount:rows.length}}
export function dedupeRecords(records:WaybackRecord[]){const map=new Map<string,WaybackRecord>();for(const record of records){const current=map.get(record.original);if(!current||record.timestamp>current.timestamp)map.set(record.original,record)}return[...map.values()]}
export function filterWayback(records:WaybackRecord[],filters:WaybackFilters){const search=filters.search.trim().toLowerCase();return records.filter(record=>(!search||record.searchText.includes(search))&&(filters.status==="all"||(filters.status==="unknown"?record.status===null:record.status!==null&&Math.floor(record.status/100)===Number(filters.status[0])))&&(filters.type==="ALL"||record.type===filters.type)&&(!filters.interesting||record.isInteresting)&&(!filters.params||record.hasParams)).sort((a,b)=>filters.sort==="newest"?b.timestamp.localeCompare(a.timestamp):filters.sort==="oldest"?a.timestamp.localeCompare(b.timestamp):filters.sort==="status"?(a.status??999)-(b.status??999):filters.sort==="type"?a.type.localeCompare(b.type)||a.path.localeCompare(b.path):a.path.localeCompare(b.path))}
export const copyRecords=(records:WaybackRecord[])=>records.map(record=>record.original).join("\n");
export function summarizeWayback(records:WaybackRecord[]){const years=records.map(record=>record.timestamp.slice(0,4)).sort();return{total:records.length,js:records.filter(x=>x.type==="JS").length,api:records.filter(x=>x.isApiLike).length,params:records.filter(x=>x.hasParams).length,range:years.length?`${years[0]} → ${years.at(-1)}`:"—"}}

export type WaybackClientError="timeout"|"rate-limit"|"unavailable"|"invalid"|"cancelled"|"network";
export async function fetchWaybackPage(target:TargetContext,scope:WaybackScope,page:number,signal:AbortSignal,fetcher:typeof fetch=fetch):Promise<WaybackPage>{const timeout=new AbortController();const timer=setTimeout(()=>timeout.abort(),12000);const abort=()=>timeout.abort();signal.addEventListener("abort",abort,{once:true});try{const response=await fetcher(buildCdxUrl(target,scope,page),{method:"GET",credentials:"omit",cache:"no-store",signal:timeout.signal});if(response.status===429)throw new Error("rate-limit");if(!response.ok)throw new Error(response.status>=500?"unavailable":"network");let json:unknown;try{json=await response.json()}catch(parseError){throw new Error("invalid",{cause:parseError})}return parseCdxJson(json,page)}catch(error){if(signal.aborted)throw new Error("cancelled",{cause:error});if(timeout.signal.aborted)throw new Error("timeout",{cause:error});throw error instanceof Error?error:new Error("network",{cause:error})}finally{clearTimeout(timer);signal.removeEventListener("abort",abort)}}
