import {describe,expect,it} from "vitest";
import {archiveUrl,buildCdxUrl,classifyArchivedUrl,copyRecords,dedupeRecords,fetchWaybackPage,filterWayback,parseCdxJson,rootDomain,summarizeWayback,waybackScope,type WaybackFilters} from "./wayback";
import type {TargetContext} from "../../types";
const target:TargetContext={originalInput:"https://www.example.com/x",normalizedUrl:"https://www.example.com/x",protocol:"https:",origin:"https://www.example.com",hostname:"www.example.com",port:null,pathname:"/x",search:"",isCurrentTab:true};
const fixture=[["timestamp","original","statuscode","mimetype","digest"],["20240102030405","https://www.example.com/index.html","200","text/html","a"],["20230102030405","https://www.example.com/index.html","200","text/html","b"],["20240202030405","https://www.example.com/assets/app.js","200","application/javascript","c"],["20240302030405","https://www.example.com/api/v1/users?q=x","200","application/json","d"],["20240402030405","https://www.example.com/admin","302","text/html","e"],["20240502030405","https://www.example.com/backup/config.bak","404","text/plain","f"]];
describe("Wayback intelligence",()=>{
  it("builds bounded CDX URLs and target scopes",()=>{const url=buildCdxUrl(target,"host",2);expect(url.origin).toBe("https://web.archive.org");expect(url.searchParams.get("url")).toBe("www.example.com/*");expect(url.searchParams.get("fl")).toBe("timestamp,original,statuscode,mimetype,digest");expect(url.searchParams.get("collapse")).toBe("urlkey");expect(url.searchParams.get("limit")).toBe("500");expect(url.searchParams.get("page")).toBe("2");expect(rootDomain("app.example.com.tr")).toBe("example.com.tr");expect(waybackScope(target,"root")).toBe("example.com/*")});
  it("parses, classifies and deduplicates deterministic rows",()=>{const page=parseCdxJson(fixture);expect(page.records).toHaveLength(5);expect(page.records.find(x=>x.type==="JS")).toBeTruthy();expect(page.records.find(x=>x.isApiLike&&x.hasParams)).toBeTruthy();expect(page.records.find(x=>x.extension==="bak")?.isInteresting).toBe(true);expect(dedupeRecords([...page.records,{...page.records[0],timestamp:"20250102030405"}])[0].timestamp).toBe("20250102030405")});
  it("composes status, type, params, interesting, search and sort filters",()=>{const records=parseCdxJson(fixture).records;const base:WaybackFilters={search:"",status:"all",type:"ALL",interesting:false,params:false,sort:"path"};expect(filterWayback(records,{...base,status:"2xx",type:"API",params:true})).toHaveLength(1);expect(filterWayback(records,{...base,interesting:true}).length).toBe(3);expect(filterWayback(records,{...base,search:"admin"})[0].status).toBe(302);expect(filterWayback(records,{...base,sort:"newest"})[0].timestamp).toBe("20240502030405")});
  it("builds copy output, archive URLs and summaries",()=>{const records=parseCdxJson(fixture).records;expect(copyRecords(records).split("\n")).toHaveLength(5);expect(archiveUrl(records[0])).toBe("https://web.archive.org/web/20240102030405id_/https://www.example.com/index.html");expect(summarizeWayback(records)).toMatchObject({total:5,js:1,api:1,params:1,range:"2024 → 2024"})});
  it("classifies long and malformed inputs without throwing",()=>{expect(classifyArchivedUrl(`https://x.test/${"a".repeat(2100)}.pdf`).type).toBe("DOCS");expect(classifyArchivedUrl("invalid").type).toBe("HTML");expect(()=>parseCdxJson({})).toThrow("INVALID_RESPONSE")});
  it("maps rate limits, service errors, invalid JSON and cancellation",async()=>{const signal=new AbortController().signal;const response=(status:number,body="[]")=>new Response(body,{status});await expect(fetchWaybackPage(target,"host",0,signal,async()=>response(429))).rejects.toThrow("rate-limit");await expect(fetchWaybackPage(target,"host",0,signal,async()=>response(503))).rejects.toThrow("unavailable");await expect(fetchWaybackPage(target,"host",0,signal,async()=>response(200,"not json"))).rejects.toThrow("invalid");const cancelled=new AbortController();cancelled.abort();await expect(fetchWaybackPage(target,"host",0,cancelled.signal,async()=>{throw new DOMException("Aborted","AbortError")})).rejects.toThrow("cancelled")});
});
